// lib/vue/UniDraw.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { UniDraw } from '../UniDraw'
import type { UniDrawOptions } from '../UniDraw'
import type { EdgeData, GraphData, NodeData } from '../shared/types'

// ─── Props ────────────────────────────────────────────────────────────────

const props = withDefaults(defineProps<{
  modelValue?: GraphData
  showShapePanel?: boolean
  showToolbar?: boolean
  grid?: boolean
  snapline?: boolean
  readonly?: boolean
  assets?: UniDrawOptions['assets']
  assetPage?: UniDrawOptions['assetPage']
  assetTotalPages?: UniDrawOptions['assetTotalPages']
  assetPageLoading?: UniDrawOptions['assetPageLoading']
  canPrevAssets?: UniDrawOptions['canPrevAssets']
  canNextAssets?: UniDrawOptions['canNextAssets']
  templates?: UniDrawOptions['templates']
}>(), {
  showShapePanel: true,
  showToolbar: true,
  grid: true,
  snapline: true,
  readonly: false,
  assetPage: 1,
  assetTotalPages: 1,
  assetPageLoading: false,
  canPrevAssets: false,
  canNextAssets: false,
})

// ─── Emits ────────────────────────────────────────────────────────────────

const emit = defineEmits<{
  (e: 'update:modelValue', data: GraphData): void
  (e: 'ready'): void
  (e: 'selection:change', nodes: NodeData[], edges: EdgeData[]): void
  (e: 'assets:prev-page'): void
  (e: 'assets:next-page'): void
}>()

// ─── Instance ─────────────────────────────────────────────────────────────

const containerRef = ref<HTMLElement | null>(null)
let instance: UniDraw | null = null

onMounted(() => {
  if (!containerRef.value)
    return
  instance = new UniDraw(containerRef.value, {
    initialData: props.modelValue,
    assets: props.assets,
    assetPage: props.assetPage,
    assetTotalPages: props.assetTotalPages,
    assetPageLoading: props.assetPageLoading,
    canPrevAssets: props.canPrevAssets,
    canNextAssets: props.canNextAssets,
    onAssetsPrevPage: () => emit('assets:prev-page'),
    onAssetsNextPage: () => emit('assets:next-page'),
    templates: props.templates,
    showShapePanel: props.showShapePanel,
    showToolbar: props.showToolbar,
    grid: props.grid,
    snapline: props.snapline,
    readonly: props.readonly,
    onReady: () => emit('ready'),
    onSelectionChange: (nodes, edges) => emit('selection:change', nodes, edges),
    onDataChange: data => emit('update:modelValue', data),
  })
})

onBeforeUnmount(() => { instance?.destroy(); instance = null })

// Sync external v-model changes into the canvas
watch(() => props.modelValue, (val) => {
  if (val && instance)
    instance.setData(val)
})

watch(() => props.assets, (val) => {
  if (instance && val)
    instance.setAssets(val)
})

watch(() => props.templates, (val) => {
  if (instance && val)
    instance.setTemplates(val)
})

watch(
  () => [props.assetPage, props.assetTotalPages, props.assetPageLoading, props.canPrevAssets, props.canNextAssets] as const,
  () => {
    instance?.setAssetPagination({
      assetPage: props.assetPage,
      assetTotalPages: props.assetTotalPages,
      assetPageLoading: props.assetPageLoading,
      canPrevAssets: props.canPrevAssets,
      canNextAssets: props.canNextAssets,
      onAssetsPrevPage: () => emit('assets:prev-page'),
      onAssetsNextPage: () => emit('assets:next-page'),
    })
  },
)

// ─── Expose ───────────────────────────────────────────────────────────────

defineExpose({
  getData: () => instance?.getData(),
  setData: (d: GraphData) => instance?.setData(d),
  clear: () => instance?.clear(),
  exportPNG: () => instance?.exportPNG(),
  exportSVG: () => instance?.exportSVG(),
  exportJSON: () => instance?.exportJSON(),
  undo: () => instance?.undo(),
  redo: () => instance?.redo(),
  zoomIn: () => instance?.zoomIn(),
  zoomOut: () => instance?.zoomOut(),
  zoomFit: () => instance?.zoomFit(),
  selectAll: () => instance?.selectAll(),
  deleteSelection: () => instance?.deleteSelection(),
})
</script>

<template>
  <div ref="containerRef" style="width:100%;height:100%;overflow:hidden" />
</template>

// lib/react/UniDraw.tsx
import { useRef, useEffect, useImperativeHandle, forwardRef } from 'react'
import type { CSSProperties } from 'react'
import { UniDraw as UniDrawCore } from '../UniDraw'
import type { UniDrawOptions } from '../UniDraw'
import type { GraphData, NodeData, EdgeData } from '../shared/types'

// ─── Public props / ref types ──────────────────────────────────────────────

export interface UniDrawProps extends Omit<UniDrawOptions, 'initialData' | 'onReady' | 'onAiGenerate' | 'onSelectionChange' | 'onDataChange'> {
  value?: GraphData
  onReady?: () => void
  onSelectionChange?: (nodes: NodeData[], edges: EdgeData[]) => void
  onChange?: (data: GraphData) => void
  style?: CSSProperties
  className?: string
}

export interface UniDrawRef {
  getData(): GraphData | undefined
  setData(data: GraphData): void
  clear(): void
  exportPNG(): Promise<string | undefined>
  exportSVG(): Promise<string | undefined>
  exportJSON(): string | undefined
  openTemplatePanel(): void
  undo(): void
  redo(): void
  zoomIn(): void
  zoomOut(): void
  zoomFit(): void
  selectAll(): void
  deleteSelection(): void
}

// ─── Component ─────────────────────────────────────────────────────────────

const UniDraw = forwardRef<UniDrawRef, UniDrawProps>(function UniDraw(props, ref) {
  const {
    value, onReady, onSelectionChange, onChange,
    style, className,
    ...opts
  } = props

  const containerRef = useRef<HTMLDivElement>(null)
  const instanceRef  = useRef<UniDrawCore | null>(null)

  useEffect(() => {
    if (!containerRef.current) return
    const inst = new UniDrawCore(containerRef.current, {
      ...opts,
      initialData:      value,
      onReady,
      onSelectionChange,
      onDataChange:     onChange,
    })
    instanceRef.current = inst
    return () => { inst.destroy(); instanceRef.current = null }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // Sync external value changes
  useEffect(() => {
    if (value && instanceRef.current) instanceRef.current.setData(value)
  }, [value])

  useEffect(() => {
    if (instanceRef.current && props.assets) instanceRef.current.setAssets(props.assets)
  }, [props.assets])

  useEffect(() => {
    instanceRef.current?.setAssetPagination({
      assetPage: props.assetPage,
      assetTotalPages: props.assetTotalPages,
      assetPageLoading: props.assetPageLoading,
      canPrevAssets: props.canPrevAssets,
      canNextAssets: props.canNextAssets,
      onAssetsPrevPage: props.onAssetsPrevPage,
      onAssetsNextPage: props.onAssetsNextPage,
    })
  }, [
    props.assetPage,
    props.assetTotalPages,
    props.assetPageLoading,
    props.canPrevAssets,
    props.canNextAssets,
    props.onAssetsPrevPage,
    props.onAssetsNextPage,
  ])

  useEffect(() => {
    if (instanceRef.current && props.templates) instanceRef.current.setTemplates(props.templates)
  }, [props.templates])

  useImperativeHandle(ref, () => ({
    getData:         () => instanceRef.current?.getData(),
    setData:         (d)          => instanceRef.current?.setData(d),
    clear:           ()           => instanceRef.current?.clear(),
    exportPNG:       ()           => instanceRef.current?.exportPNG() ?? Promise.resolve(undefined),
    exportSVG:       ()           => instanceRef.current?.exportSVG() ?? Promise.resolve(undefined),
    exportJSON:      ()           => instanceRef.current?.exportJSON(),
    openTemplatePanel: ()         => instanceRef.current?.openTemplatePanel(),
    undo:            ()           => instanceRef.current?.undo(),
    redo:            ()           => instanceRef.current?.redo(),
    zoomIn:          ()           => instanceRef.current?.zoomIn(),
    zoomOut:         ()           => instanceRef.current?.zoomOut(),
    zoomFit:         ()           => instanceRef.current?.zoomFit(),
    selectAll:       ()           => instanceRef.current?.selectAll(),
    deleteSelection: ()           => instanceRef.current?.deleteSelection(),
  }))

  return (
    <div
      ref={containerRef}
      className={className}
      style={{ width: '100%', height: '100%', overflow: 'hidden', ...style }}
    />
  )
})

export default UniDraw
